name: Code Quality Checks

on: [push, pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Initialize project and install dependencies
        run: |
          npm init -y
          npm install htmlhint stylelint stylelint-config-standard --save-dev

      # Run HTMLHint (no autofix)
      - name: Run HTMLHint
        run: npx htmlhint "**/*.html" --config .htmlhintrc || true

      # Create default stylelint config if missing
      - name: Create default .stylelintrc.json
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json
        if: ${{ !hashFiles('.stylelintrc.json') }}

      # Run stylelint with autofix
      - name: Run Stylelint with Autofix
        run: npx stylelint "**/*.css" --fix
